/* config.h.  Generated by configure.  */
#ifndef __LIBDRA_CONFIG_H__
#define __LIBDRA_CONFIG_H__


#define INPUT_BUFFER_SIZE		(4*1024)

#define MAX_CLUSTER_NUM			3
#define MAX_HSBANDEDGE			32
#define MAX_FRAMELENGTH			1024
#define MAX_CBANDNUM			23
#define MAX_CHANNEL				8

# define F_FRACBITS		28
# define F_ONE			0x10000000
#define MAX_32			(int)0x7fffffffL
#define MIN_32			(int)0x80000000L

#define MAX_16			(short)0x7fff
#define MIN_16			(short)0x8000

#ifndef MAX
#define MAX(a,b)	((a) > (b) ? (a) : (b))
#endif

#ifndef MIN
#define MIN(a,b)	((a) < (b) ? (a) : (b))
#endif

#ifndef NULL
#define  NULL 0
#endif

#endif