#ifndef _NCNAMETAB_H_
#define _NCNAMETAB_H_
#include "defines.h"
#define GetBlockLumaNxNInBound				ARM_GB1
#define GetBlockChromaNxNInBound			ARM_GB2
#if RENAME_BP

#if defined (_IOS) || defined(_MAC_OS) || defined(_LINUX) 
#define  VOH264CreateEvent                            VOH264CreateEventBP 
#define  VOH264SetEvent                               VOH264SetEventBP 
#define  VOH264ResetEvent                             VOH264ResetEventBP 
#define  VOH264WaitForEvent                           VOH264WaitForEventBP 
#define  VOH264DestroyEvent                           VOH264DestroyEventBP
#endif

#ifdef USE_JOBPOOL
#define  parsembs                                parsembsBP
#define  InitJobPool                              InitJobPoolBP
#define  ExitJobPool                              ExitJobPoolBP
#define  AddAJobToPool                       AddAJobToPoolBP
#define  WaitForJobFromPool              WaitForJobFromPoolBP
#define  IsReadyDecode2                    IsReadyDecode2BP
#define  restart_cores                          restart_coresBP
#define voH264OS_Sleep                          voH264OS_SleepBP
#endif

#define GetVLCSymbol_NEW						GetVLCSymbol_NEW80
#define readCoeff4x4_CAVLC						readCoeff4x4_CAVLC81
#define avdNumLeadingZerosPlus1					avdNumLeadingZerosPlus108
#define LsbOnes									LsbOnes69
#define FlushBits								FlushBits75
#define ShowBits								ShowBits76
#define SetInPlaceInterMBStrength				SETINMS
#define GetBlockLumaNxN							GetBlockLumaNxN08
#define GetBlockChromaNxN						GetBlockChromaNxN09
#define intrapred_luma_16x16					intrapred_luma_16x1612
#define itrans									itrans03
#define intrapred								intrapred11

#define intrapred_chroma_uv						intrapred_chroma_uv13
//#define itrans_2								__voH264D0014itrans
#define itrans_old								itrans_old15
#define itrans_sp_chroma						itrans_sp_chroma16
#define itrans_sp								itrans_sp17

#define GetAnnexbNALU							GetAnnexbNALU01
#define OpenBitstreamFile						OpenBitstreamFile02
#define CloseBitstreamFile						CloseBitstreamFile03
#define StartAriDeco							StartAriDecoBP


///XXXXXXXX_TOBEUSED						__voH264D0030
#define alloc_motion_info						alloc_motion_infoBP
#define get_motion_info							get_motion_info44
#define FreeMotionInfo							FreeMotionInfo45
#define PutMotionInfo							PutMotionInfo46
#define InitStorablePic							InitStorablePic47
#define GetStorablePic							GetStorablePic48
#define PutStorablePic							PutStorablePic49
#define init_contexts							init_contexts50
#define CeilLog2								CeilLog251
#define FirstPartOfSliceHeader					FirstPartOfSliceHeader52
#define RestOfSliceHeader						RestOfSliceHeader53
#define pred_weight_table						pred_weight_table54
#define dec_ref_pic_marking						dec_ref_pic_marking55
#define decode_poc								decode_poc56
#define picture_order							picture_order57
#define CheckInBufOverFlow						CheckInBufOverFlow58
#define H264ReceiveDataPack						H264ReceiveDataPack59
#define ProcessOneNALU							ProcessOneNALU61
#define MovePartialDataForEBSPtoRBSP			MovePartialDataForEBSPtoRBSP62
#define FmoGenerateMapUnitToSliceGroupMap		FmoGenerateMapUnitToSliceGroupMap65
#define FmoGenerateMbToSliceGroupMap			FmoGenerateMbToSliceGroupMap66
#define FmoInit									FmoInit67
#define FmoFinit								FmoFinit68
#define FmoGetNumberOfSliceGroup				FmoGetNumberOfSliceGroup69
#define FmoGetLastMBOfPicture					FmoGetLastMBOfPicture70
#define FmoGetLastMBInSliceGroup				FmoGetLastMBInSliceGroup71
#define FmoGetSliceGroupId						FmoGetSliceGroupId72
#define FmoGetNextMBNr							FmoGetNextMBNr73
#define FmoGenerateType0MapUnitMap				FmoGenerateType0MapUnitMap74
#define FmoGenerateType1MapUnitMap				FmoGenerateType1MapUnitMap75
#define FmoGenerateType2MapUnitMap				FmoGenerateType2MapUnitMap76
#define FmoGenerateType3MapUnitMap				FmoGenerateType3MapUnitMap77
#define FmoGenerateType4MapUnitMap				FmoGenerateType4MapUnitMap78
#define FmoGenerateType5MapUnitMap				FmoGenerateType5MapUnitMap79
#define FmoGenerateType6MapUnitMap				FmoGenerateType6MapUnitMap80
#define InitSliceList							InitSliceList082
#define DeInitSliceList							DeInitSliceList083
#define MbAffPostProc							MbAffPostProc084
#define preprocess_one_frame					preprocess_one_frame085
#define preprocess_one_pic						preprocess_one_pic086
#define process_one_slice						process_one_slice087
#define postprocess_one_pic						postprocess_one_pic88
#define postprocess_one_frame					postprocess_one_frame89
#define get_block								get_block90
#define read_new_slice							read_new_slice91
#define set_ref_pic_num							set_ref_pic_num92
#define init_frame							init_frame93
#define ExpandYUVPlane							ExpandYUVPlane94
#define uninit_frame2								uninit_frame295
#define uninit_frame								uninit_frame96
#define ercWriteMBMODEandMV						__ercWriteMBMODEandMV097
#define init_old_slice							__init_old_slice098
#define exit_slice								exit_slice099
#define is_new_picture							is_new_picture100
#define decode_slice							decode_slice101
#define frame_postprocessing					frame_postprocessing102
#define field_postprocessing					field_postprocessing103
#define fill_wp_params							fill_wp_params104
#define deInitDec								deInitDec105
#define initDec									initDecD0106
#define InitClipArrs							InitClipArrs0107
#define DeInitClipArrs							DeInitClipArrs108
#define AllocPartition							AllocPartition109
#define FreePartition							FreePartition110
#define malloc_slice							malloc_slice111
#define free_slice								free_slice112
#define init_global_buffers						init_global_buffers113
#define free_global_buffers						free_global_buffers114
#define InPlaceDeblockMBs						InPlaceDeblockMBs15
//#define SetInPlaceInterMBStrength				__voH264D0116		the ARMV5_inplaceDeblock refers the symbol,so do not change it
#define SetInPlaceIntraMBStrength				SetInPlaceIntraMBStrength17	
#define DeblockFrame							__voH264D0118
#define DeblockFrameAllCases					__voH264D0119
#define DeblockFrameNonMbaff					__voH264D0120
#define IPP_DeblockFrameNonMbaff				__voH264D0121
#define IPP_SetMBStrength						__voH264D0122
#define DIVIDE6									__voH264D0123
#define mbInTheSameSlice						__voH264D0124
#define start_macroblock						__voH264D0125
#define exit_macroblock							__voH264D0126
#define GetNeighborAB							__voH264D0127
#define Get_Neighbor_ABCnRefIdx					__voH264D0128
#define SetMotionVectorPredictor				__voH264D0129
#define initArray4AllMacroblock					__voH264D0134
#define SetB8Mode								__voH264D0135
#define read_ipred_modes_CAVLC						read_ipred_modes_CAVLCBP
#define StoreInPlaceDeblockTopLine				StoreInPlaceDeblockTopLineBP
#define decode_one_slice						decode_one_sliceBP
#define init_decoding_engine_IPCM				init_decoding_engine_IPCMBP
#define readIPCMcoeffsFromNAL					readIPCMcoeffsFromNALBP
#define decode_ipcm_mb							decode_ipcm_mbBP
#define voH264AlignedMalloc							__voH264D0145
#define voH264AlignedFree								__voH264D0146
#define get_mem2D								get_mem2DBP
#define get_mem3D								get_mem3DBP
#define free_mem2D								__voH264D0149
#define free_mem3D								__voH264D0150
#define no_mem_exit								__voH264D0151
#define getDpbSize								__voH264D0152
#define init_dpb								__voH264D0153
#define free_dpb								__voH264D0154
#define alloc_frame_store						__voH264D0155
#define AllocImgYArray							__voH264D0156
#define AllocImgUVArray							__voH264D0157
#define FreeImgYArray							__voH264D0158
#define FreeImgUVArray							__voH264D0159
#define alloc_storable_picture					__voH264D0160
#define free_frame_store						__voH264D0161
#define free_storable_picture					__voH264D0162
#define unmark_for_reference					__voH264D0163
#define unmark_for_long_term_reference			__voH264D0164
#define compare_pic_by_pic_num_desc				__voH264D0165
#define compare_pic_by_lt_pic_num_asc			__voH264D0166
#define compare_fs_by_frame_num_desc			__voH264D0167
#define compare_fs_by_lt_pic_idx_asc			__voH264D0168
#define compare_pic_by_poc_asc					__voH264D0169
#define compare_pic_by_poc_desc					__voH264D0170
#define compare_fs_by_poc_asc					__voH264D0171
#define compare_fs_by_poc_desc					__voH264D0172
#define is_short_ref							__voH264D0173
#define is_long_ref								__voH264D0174
#define gen_pic_list_from_frame_list			__voH264D0175
#define init_lists								__voH264D0176
#define init_mbaff_lists						__voH264D0177
#define get_short_term_pic						__voH264D0178
#define get_long_term_pic						__voH264D0179
#define reorder_short_term						__voH264D0180
#define reorder_long_term						__voH264D0181
#define reorder_ref_pic_list					__voH264D0182
#define update_ref_list							__voH264D0183
#define update_ltref_list						__voH264D0184
#define idr_memory_management					__voH264D0185
#define sliding_window_memory_management		__voH264D0186
#define get_pic_num_x							__voH264D0187
#define mm_unmark_short_term_for_reference									__voH264D0188
#define mm_unmark_long_term_for_reference									__voH264D0189
#define unmark_long_term_frame_for_reference_by_frame_idx					__voH264D0190
#define unmark_long_term_field_for_reference_by_frame_idx					__voH264D0191
#define mark_pic_long_term						__voH264D0192
#define mm_assign_long_term_frame_idx			__voH264D0193
#define mm_update_max_long_term_frame_idx		__voH264D0194
#define mm_unmark_all_long_term_for_reference	__voH264D0195
#define mm_unmark_all_short_term_for_reference	__voH264D0196
#define mm_mark_current_picture_long_term		__voH264D0197
#define adaptive_memory_management				__voH264D0198
#define store_picture_in_dpb					__voH264D0199
#define insert_picture_in_dpb					__voH264D0200
#define is_used_for_reference					__voH264D0201
#define is_short_term_reference					__voH264D0202
#define is_long_term_reference					__voH264D0203
#define remove_frame_from_dpb					__voH264D0204
#define get_smallest_poc						__voH264D0205
#define remove_unused_frame_from_dpb			__voH264D0206
#define output_one_frame_from_dpb				__voH264D0207
#define flush_dpb								__voH264D0208
#define alloc_ref_pic_list0_reordering_buffer	__voH264D0209
#define free_ref_pic_list0_reordering_buffer	__voH264D0210
#define DpbFrPostProc							__voH264D0211
#define alloc_ref_pic_list1_reordering_buffer	__voH264D0212
#define free_ref_pic_list1_reordering_buffer	__voH264D0213
#define fill_frame_num_gap						__voH264D0214
#define dpb_split_field							__voH264D0215
#define DpbFldPostProc							__voH264D0216
#define DpbCombineYUVFields						__voH264D0217
#define dpb_combine_field						__voH264D0218
#define RBSPtoSODB								__voH264D0219
#define EBSPtoRBSP								__voH264D0220
#define NALUtoRBSP								__voH264D0221
#define avd_assignSE2partition					__voH264D0222
#define Alloc_Neighbor_Info						__voH264D0223
#define Free_Neighbor_Info						__voH264D0224
#define Init_Slice_Neighbor_Info				__voH264D0225
#define update_MB_neighbor_info					__voH264D0226
#define update_neighborABCD_info				__voH264D0227
#define Init_MB_Neighbor_Info					__voH264D0228
#define Finish_MB_Neighbor_Info					__voH264D0229
#define NeighborAB_Inference_CABAC				__voH264D0230
#define write_picture							__voH264D0231
#define init_out_buffer							__voH264D0232
#define uninit_out_buffer						__voH264D0233
#define clear_picture							__voH264D0234
#define write_unpaired_field					__voH264D0235
#define flush_direct_output						__voH264D0236
#define write_stored_frame						__voH264D0237
#define direct_output							__voH264D0238
#define ReadHRDParameters						__voH264D0239
#define ReadVUI									ReadVUIBP
#define InterpretSPS							InterpretSPSBP
#define InterpretPPS							InterpretPPSBP
#define ProcessSPS								__voH264D0243
#define SPSConsistencyCheck						__voH264D0244
#define ProcessPPS								ProcessPPSBP
#define UpdateSizeNActivateSPS					__voH264D0246
#define UseParameterSet							__voH264D0247
#define interpret_recovery_point_info			__voH264D0248
#define InterpretSEIMessage						__voH264D0249
#define interpret_spare_pic						__voH264D0250
#define interpret_subsequence_info				__voH264D0251
#define interpret_subsequence_layer_characteristics_info				__voH264D0252
#define interpret_subsequence_characteristics_info						__voH264D0253
#define interpret_scene_information										__voH264D0254
#define interpret_filler_payload_info									__voH264D0255
#define interpret_user_data_unregistered_info							__voH264D0256
#define interpret_user_data_registered_itu_t_t35_info					__voH264D0257
#define interpret_pan_scan_rect_info									__voH264D0258
#define interpret_dec_ref_pic_marking_repetition_info					__voH264D0259
#define interpret_full_frame_freeze_info								__voH264D0260
#define interpret_full_frame_freeze_release_info						__voH264D0261
#define interpret_full_frame_snapshot_info								__voH264D0262
#define interpret_progressive_refinement_start_info						__voH264D0263
#define interpret_progressive_refinement_end_info						__voH264D0264
#define interpret_motion_constrained_slice_group_set_info				__voH264D0265
#define interpret_reserved_info											__voH264D0266
#define interpret_buffering_period_info									__voH264D0267
#define interpret_picture_timing_info									__voH264D0268
//#define LsbOnes									__voH264D0269
#define InitBitStream							__voH264D0270
#define avd_se_v								__voH264D0271
#define readVLCSynElement_Ue					__voH264D0272
#define readVLCSynElement_Se					__voH264D0273
#define uvlc_startcode_follows					__voH264D0274
//#define FlushBits								__voH264D0275
//#define ShowBits								__voH264D0276
#define GetBits									__voH264D0277
#define GetCavlcCoeff4x4NeighborContextIdx		__voH264D0278

//#define decode_one_macroblock					__voH264D0279
//#define GetVLCSymbol_NEW						__voH264D0280
//#define readCoeff4x4_CAVLC						__voH264D0281
#define DpbBaselinePlusBFrMBRowPostProc			__voH264D0282
// multiple skipped MBs
#define GetSkipMBsInARow						__voH264D0300
#define GetPSliceSkippedMV						__voH264D0301
#define GetGroupInterMBs						__voH264D0302
			
//Platform_Dependent_For_C_Code xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#define biari_decode_symbol						__voH264D1000
#define SILumaAvgBlock							__voH264D1001
#define SIChromaAvgBlock						__voH264D1002

#define itrans_LeftHalf							__voH264D1004
#define AllocateHalfPelBuffer					__voH264D1005
#define FreeHalfPelBuffer						__voH264D1006
#define ClearHalfPelBuffer						__voH264D1007

//#define error								__voH264D0081

//more

#define setLimit								__voH264D1105
#define DUMPData								__voH264D1106
#define AvdLogPOC								__voH264D1107
#define resetDec								__voH264D1108
#define InitRefBuffer							__voH264D1110
#define OutPutCallBack							__voH264D1111
#define OutputFirstFrame						__voH264D1112
#define ProcessDPBAfterError					__voH264D1113
#define AvdLogBitmapFile						__voH264D1114
#define UpdateSize								__voH264D1116
#define PPSConsistencyCheck						__voH264D1117
#define SetStrengthOne							__voH264D1118
#define SetStrengthOne2							__voH264D1119
#define FIELD_SCAN_TO_INDEX						__voH264D1120
#define SNGL_SCAN_TO_INDEX						__voH264D1121

#define chromaScan								__voH264D1125
#define dequant_coef							__voH264D1126
#define QP_SCALE_CR								__voH264D1127
#define avd_NCBP								__voH264D1128
#define offset2pdir16x16						__voH264D1129
#define offset2pdir16x8							__voH264D1130
#define offset2pdir8x16							__voH264D1131
#define avd_rLPS_table_64x4						__voH264D1132
#define avd_AC_next_state_MPS_64				__voH264D1133
#define avd_AC_next_state_LPS_64				__voH264D1134
#define ALPHA_TABLE								__voH264D1135
#define BETA_TABLE								__voH264D1136
#define CLIP_TAB								__voH264D1137
#define BLK_NUM									__voH264D1138
#define nal_startcode_follows					__voH264D1140
#define SliceList								__voH264D1141
#define decode_slice_jmp						__voH264D1142
#define AvdLogSliceHeader						__voH264D1144
#define dump_dpb								__voH264D1145
//ASSEMBLY 
#define itrans_2								__voH264D1146
//#define AvdLog2									__voH264D1147
//#define img										imgBP
#define GetCurrentImgType						GetCurrentImgTypeBP
#define H264ProbeStream							H264ProbeStreamBP
#define H264VdLibStartDecode					H264VdLibStartDecodeBP
#define H264VdLibEndDecode						H264VdLibEndDecodeBP
#define H264Flushing							H264FlushingBP
#define GetH264Profile							GetH264ProfileBP
#define H264DecodeHeadDataAnnexB			H264DecodeHeadDataAnnexBBP
#define voH264DecProcessNALU voH264DecProcessNALUBP
#define H264ReceiveData H264ReceiveDataBP

#define voH264DecProcessAnnexB voH264DecProcessAnnexBBP
#define voH264DecInitNew voH264DecInitNewBP
#define voH264DecInit voH264DecInitBP
#define voH264DecProcess voH264DecProcessBP
#define voH264DecUninit voH264DecUninitBP
#define voH264DecSetParameter voH264DecSetParameterBP
#define voH264DecGetParameter voH264DecGetParameterBP
#define avd_error	avd_errorBP
#define PreAllocateBuf PreAllocateBufBP
#define ARM11_MX31Deblock ARM11_MX31DeblockBP
#define ARM11_MX31DeblockUnInit ARM11_MX31DeblockUnInitBP
#define ARM11_MX31DeblockInit ARM11_MX31DeblockInitBP
#define ARM11_MX31SetDBStrength ARM11_MX31SetDBStrengthBP
#define DumpReusedInfo DumpReusedInfoBP
#define DumpRefList DumpRefListBP
#define DumpPicBuf DumpPicBufBP
#define DumpBufInfo DumpBufInfoBP
#define Try_output_one_frame_from_dpb Try_output_one_frame_from_dpbBP
#define gRefFrame gRefFrameBP
#define BLOCK_STEP BLOCK_STEPBP
#define T8x8KPos T8x8KPosBP
#define T8x8Offset1 T8x8Offset1BP
#define decode_scan decode_scanBP
#define inv_decode_scan inv_decode_scanBP
#define DumpMBBeforeDeblock DumpMBBeforeDeblockBP
#define Dumploop DumploopBP
#define Dumploop2 Dumploop2BP
#define decode_one_macroblock decode_one_macroblockBP
#define IPredName4x4 IPredName4x4BP
#define IPredName16x16 IPredName16x16BP
#define IPredName8x8 IPredName8x8BP
#define MBModeName MBModeNameBP
#define MCDirName MCDirNameBP
#define dumpNumItrans dumpNumItransBP
#define ItransTpName ItransTpNameBP
#define dmpSeqFp dmpSeqFpBP
#define gLogFile2 gLogFile2BP
#define InitDump InitDumpBP
#define DeInitDump DeInitDumpBP
#define GetStrFrameType GetStrFrameTypeBP
#define StoreErrorFrame StoreErrorFrameBP
#define IMX31_AddOneFrame IMX31_AddOneFrameBP
#define voH264DecProcessAVC voH264DecProcessAVCBP
#define imgType imgTypeBP
#define CHECK_MOTIONINFO CHECK_MOTIONINFOBP
#define GetBitStreamLeadingOne GetBitStreamLeadingOneBP
#define PeekBitStreamLeadingOne PeekBitStreamLeadingOneBP
#define _dmpDblkFp dmpDblkFpBP
#define _dmpSlcFp  dmpSlcFpBP
#define _dmpSlcFpData dmpSlcFpDataBP
#define _dumpNumItrans dumpNumItransItrans
#define _dmpSeqFp dmpSeqFpBP
#define _dumpSkipped dumpSkippedBP
#define _dumpStartFrameNo dumpStartFrameNoBP
#define _dumpEndFrameNo dumpEndFrameNoBP
/*
#define gLogLevel gLogLevelBP
#define voH264Memset voH264MemsetBP
#define voH264Printf voH264PrintfBP
#define voPrintf voPrintfBP
#define voH264Sprintf voH264SprintfBP
#define voH264Memcpy voH264MemcpyBP
#define voH264Memmove voH264MemmoveBP
#define voH264Calloc voH264CallocBP
#define voH264Free voH264FreeBP
#define voH264IntDiv voH264IntDivBP
#define voH264IntMod voH264IntModBP

#define InitLog2 InitLog2BP
#define UninitLog2 UninitLog2BP
#define AvdOutData AvdOutDataBP
#define AvdInData AvdInDataBP
#define DUMPDataIn DUMPDataInBP
#define DUMPDataToLOG DUMPDataToLOGBP
#define AvdLog2  AvdLog2BP
*/
#define voH264DecUninit2 voH264DecUninit2BP
#define voH264DecSetParam2 voH264DecSetParam2BP
#define voH264DecGetParam2 voH264DecGetParam2BP
#define voH264DecSetInputData2 voH264DecSetInputData2BP
#define voH264DecGetOutputData2 voH264DecGetOutputData2BP
#define voH264DecInit2 voH264DecInit2BP
//#define hWin32Module hWin32ModuleBP
#define CleanOutDataQueue CleanOutDataQueueBP
#define IsThereOtherOutput IsThereOtherOutputBP
#define PopOneOutData PopOneOutDataBP
#define PushOneOutData PushOneOutDataBP
#define voCheckLibInit2 voCheckLibInit2BP
#define voCheckLibCheckVideo2 voCheckLibCheckVideo2BP
#define voCheckLibResetVideo2 voCheckLibResetVideo2BP
#define voCheckLibUninit2 voCheckLibUninit2BP

#define PreSetParam PreSetParamBP
#define interpret_mb_mode_B interpret_mb_mode_BBP
#define interpret_mb_mode_P interpret_mb_mode_PBP
#define interpret_mb_mode_I interpret_mb_mode_IBP
#define decode_one_macroblock_b_slice decode_one_macroblock_b_sliceBP
#define decode_one_macroblock_p_slice decode_one_macroblock_p_sliceBP
#define decode_one_macroblock decode_one_macroblockBP
#define read_motion_info_from_NAL_b_slice_CAVLC read_motion_info_from_NAL_b_slice_CAVLCBP
#define read_motion_info_from_NAL_pb_slice_CAVLC read_motion_info_from_NAL_pb_slice_CAVLCBP
#define read_CBP_and_coeffs_from_NAL_CABAC read_CBP_and_coeffs_from_NAL_CABACBP
#define read_CBP_and_coeffs_from_NAL_CAVLC read_CBP_and_coeffs_from_NAL_CAVLCBP
#define read_one_macroblock_pb_slice_CAVLC read_one_macroblock_pb_slice_CAVLCBP
#define read_one_macroblock_i_slice_CAVLC read_one_macroblock_i_slice_CAVLCBP
#define setup_slice_methods setup_slice_methodsBP
#define readIPCMcoeffsFromNAL_CAVLC readIPCMcoeffsFromNAL_CAVLCBP
#define decode_one_inter_macroblock decode_one_inter_macroblockBP
#define UnInitMulRowDB UnInitMulRowDBBP
#define SetMulRowStrength SetMulRowStrengthBP
#define DeblockMulRows  DeblockMulRowsBP
#define InitMulRowDB InitMulRowDBBP
#define processmbs processmbsBP
#define InitNewPicProcessor InitNewPicProcessorNP
#define ExitNewPicProcessor ExitNewPicProcessorBP
#define InitNewSliceProcessor InitNewSliceProcessorBP
#define  ExitNewSliceProcessor  ExitNewSliceProcessorBP
#define  GetMainProcessor  GetMainProcessorBP
#define  SetProcessorStatus  SetProcessorStatusBP
#define  GetProcessorStatus  GetProcessorStatusBP
#define  SetMainProcessor  SetMainProcessorBP
#define IsReadyRead IsReadyReadNP
#define IsReadyDecode IsReadyDecodeBP
#define Wait2	Wait2BP
#define CreateDCoreThread CreateDCoreThreadBP
#define ExitDCoreThread ExitDCoreThreadBP
#define DumpMbsInfo DumpMbsInfoBP
#define processmbsSingleCore processmbsSingleCoreBP

#ifdef X86_TEST
#define DumpSlice DumpSliceBP
#define AvdLog  AvdLogBP
#define _dmpSeqFp	_dmpSeqFpBP
#define _dmpDblkFp  _dmpDblkFpBP
#define _dmpSlcFp    _dmpSlcFpBP		
#define _dmpSlcFpData _dmpSlcFpDataBP
#define DumpIntraPred DumpIntraPredBP
//#define voLog_264 voLog_264BP
//#define voLog_264_debug voLog_264_debugBP
//#define voLogAndroidInfo voLogAndroidInfoBP
#define checkbits checkbitsBP
#define DumpPred DumpPredBP
#define DumpResidual DumpResidualBP
#define DumpIDCT DumpIDCTBP
#endif//X86_TEST

#ifdef TRACE_MEM
#define trace_memIssues trace_memLeakBP
#define trace_new	  trace_newBP
#define trace_delete  trace_deleteBP
#define trace_overflow trace_overflowBP
#endif//TRACE_MEM
#define DpbFrPostProc2 DpbFrPostProc2BP
#define GetBlockLumaOutBound GetBlockLumaOutBoundBP
#define GetBlockChromaOutBound GetBlockChromaOutBoundBP
#define AvdLogLevel AvdLogLevelBP
#define CheckRef CheckRefBP
#define InternalSetParam InternalSetParamBP
#define read_mbs read_mbsBP
#define decode_mbs decode_mbsBP
#define deblock_mbs deblock_mbsBP
#define ICBPTAB ICBPTABBP
//#define iClip255  iClip255BP
#define copyT35Data copyT35DataBP
#define InPlaceDeblockMBs_NEON IPDB_BP
#define SubWidthC SubWidthCBP
#define SubHeightC SubHeightCBP
#define voH264IntDiv2 voH264IntDiv2BP
#define applyWeights applyWeightsBP
#define applyWeights2 applyWeights2BP
#else//the following is name conflict
#define GetBits									voH264GetBitsMP
#endif//RENAME_BP
#endif//NCNAMETAB
