# Source files for DASH TWO file parser.
# rodney zhang
# 2012.08.09


# path variables for DASH file parser.
TRUNK_PATH:=../../../../../../..
TRUNK_INCLUDE_PATH:=$(TRUNK_PATH)/Include
TRUNK_INCLUDE_VOME_PATH:=$(TRUNK_INCLUDE_PATH)/vome
TRUNK_COMMON_PATH:=$(TRUNK_PATH)/Common
TRUNK_COMMON_BUFFER_PATH:=$(TRUNK_COMMON_PATH)/Buffer
TRUNK_COMMON_NETWORK_PATH:=$(TRUNK_COMMON_PATH)/NetWork
TRUNK_MFW_VOME_COMMON_PATH:=$(TRUNK_PATH)/MFW/voME/Common
TRUNK_UTILITY_VOUTF8CONV_PATH:=$(TRUNK_PATH)/Utility/voutf8conv

SOURCE_PATH:=$(TRUNK_PATH)/Source
SOURCE_INCLUDE_PATH:=$(SOURCE_PATH)/Include
SOURCE_COMMON_PATH:=$(SOURCE_PATH)/Common
SOURCE_FILE_PATH:=$(SOURCE_PATH)/File
SOURCE_FILE_COMMON_PATH:=$(SOURCE_PATH)/File/Common
SOURCE_FILE_COMMON_UTILITY_PATH:=$(SOURCE_FILE_COMMON_PATH)/Utility
SOURCE_ADAPTIVESTREAMING_PATH:=$(SOURCE_PATH)/AdaptiveStreaming
SOURCE_ADAPTIVESTREAMING_COMMON_PATH:=$(SOURCE_ADAPTIVESTREAMING_PATH)/Common
SOURCE_ADAPTIVESTREAMING_INCLUDE_PATH:=$(SOURCE_ADAPTIVESTREAMING_PATH)/Include
SOURCE_ADAPTIVESTREAMING_DRM_PATH:=$(SOURCE_ADAPTIVESTREAMING_PATH)/DRM
HLS_SOURCE_PATH:=$(SOURCE_PATH)/AdaptiveStreaming/HLS


# please list all directories that all source files relative with your module(.h .c .cpp) locate 
VOSRCDIR:=	\
	$(TRUNK_INCLUDE_PATH) \
	$(TRUNK_INCLUDE_VOME_PATH) \
	$(TRUNK_COMMON_PATH) \
	$(TRUNK_COMMON_BUFFER_PATH) \
	$(TRUNK_COMMON_NETWORK_PATH) \
	$(TRUNK_MFW_VOME_COMMON_PATH) \
	$(TRUNK_UTILITY_VOUTF8CONV_PATH) \
	$(SOURCE_INCLUDE_PATH) \
	$(SOURCE_COMMON_PATH) \
	$(SOURCE_FILE_COMMON_PATH) \
	$(SOURCE_FILE_COMMON_UTILITY_PATH) \
	$(SOURCE_ADAPTIVESTREAMING_COMMON_PATH) \
	$(SOURCE_ADAPTIVESTREAMING_INCLUDE_PATH) \
	$(SOURCE_ADAPTIVESTREAMING_DRM_PATH) \
	$(HLS_SOURCE_PATH)


# please list all objects needed by your module here
# List needs to be coherent, Don't insert extra comment line.
# Don't add the Common files to list, add them to the corresponding Common library
VOMSRC:= \
	$(TRUNK_COMMON_PATH)/CvoBaseObject.cpp \
	$(TRUNK_COMMON_PATH)/voCMutex.cpp \
	$(TRUNK_COMMON_PATH)/voLog.c \
	$(TRUNK_COMMON_PATH)/voOSFunc_iOS.mm \
	\
	$(SOURCE_COMMON_PATH)/vo_thread.cpp \
	$(SOURCE_COMMON_PATH)/CDataBox.cpp \
	\
	$(HLS_SOURCE_PATH)/hls_parser.cpp \
	$(HLS_SOURCE_PATH)/hls_manager.cpp \
	$(HLS_SOURCE_PATH)/hls_entity.cpp \
	$(HLS_SOURCE_PATH)/voAdaptiveStreamHLS.cpp
