cat bilinearpredict16x16_neon.asm              | perl ../../../../build/make/ads2gas.pl >bilinearpredict16x16_neon_gnu.S          
cat bilinearpredict4x4_neon.asm                | perl ../../../../build/make/ads2gas.pl >bilinearpredict4x4_neon_gnu.S            
cat bilinearpredict8x4_neon.asm                | perl ../../../../build/make/ads2gas.pl >bilinearpredict8x4_neon_gnu.S            
cat bilinearpredict8x8_neon.asm                | perl ../../../../build/make/ads2gas.pl >bilinearpredict8x8_neon_gnu.S            
cat buildintrapredictorsmby_neon.asm           | perl ../../../../build/make/ads2gas.pl >buildintrapredictorsmby_neon_gnu.S       
cat copymem16x16_neon.asm                      | perl ../../../../build/make/ads2gas.pl >copymem16x16_neon_gnu.S                  
cat copymem8x4_neon.asm                        | perl ../../../../build/make/ads2gas.pl >copymem8x4_neon_gnu.S                    
cat copymem8x8_neon.asm                        | perl ../../../../build/make/ads2gas.pl >copymem8x8_neon_gnu.S                    
cat dc_only_idct_add_neon.asm                  | perl ../../../../build/make/ads2gas.pl >dc_only_idct_add_neon_gnu.S              
cat dequant_idct_neon.asm                      | perl ../../../../build/make/ads2gas.pl >dequant_idct_neon_gnu.S                  
cat dequantizeb_neon.asm                       | perl ../../../../build/make/ads2gas.pl >dequantizeb_neon_gnu.S                   
cat idct_dequant_0_2x_neon.asm                 | perl ../../../../build/make/ads2gas.pl >idct_dequant_0_2x_neon_gnu.S             
cat idct_dequant_full_2x_neon.asm              | perl ../../../../build/make/ads2gas.pl >idct_dequant_full_2x_neon_gnu.S          
cat iwalsh_neon.asm                            | perl ../../../../build/make/ads2gas.pl >iwalsh_neon_gnu.S                        
cat loopfilter_neon.asm                        | perl ../../../../build/make/ads2gas.pl >loopfilter_neon_gnu.S                    
cat loopfiltersimplehorizontaledge_neon.asm    | perl ../../../../build/make/ads2gas.pl >loopfiltersimplehorizontaledge_neon_gnu.S
cat loopfiltersimpleverticaledge_neon.asm      | perl ../../../../build/make/ads2gas.pl >loopfiltersimpleverticaledge_neon_gnu.S  
cat mbloopfilter_neon.asm                      | perl ../../../../build/make/ads2gas.pl >mbloopfilter_neon_gnu.S                  
cat sad16_neon.asm                             | perl ../../../../build/make/ads2gas.pl >sad16_neon_gnu.S                         
cat sad8_neon.asm                              | perl ../../../../build/make/ads2gas.pl >sad8_neon_gnu.S                          
cat save_reg_neon.asm                          | perl ../../../../build/make/ads2gas.pl >save_reg_neon_gnu.S                      
cat shortidct4x4llm_neon.asm                   | perl ../../../../build/make/ads2gas.pl >shortidct4x4llm_neon_gnu.S               
cat sixtappredict16x16_neon.asm                | perl ../../../../build/make/ads2gas.pl >sixtappredict16x16_neon_gnu.S            
cat sixtappredict4x4_neon.asm                  | perl ../../../../build/make/ads2gas.pl >sixtappredict4x4_neon_gnu.S              
cat sixtappredict8x4_neon.asm                  | perl ../../../../build/make/ads2gas.pl >sixtappredict8x4_neon_gnu.S              
cat sixtappredict8x8_neon.asm                  | perl ../../../../build/make/ads2gas.pl >sixtappredict8x8_neon_gnu.S              
cat variance_neon.asm                          | perl ../../../../build/make/ads2gas.pl >variance_neon_gnu.S                      
cat vp8_subpixelvariance16x16_neon.asm         | perl ../../../../build/make/ads2gas.pl >vp8_subpixelvariance16x16_neon_gnu.S     
cat vp8_subpixelvariance16x16s_neon.asm        | perl ../../../../build/make/ads2gas.pl >vp8_subpixelvariance16x16s_neon_gnu.S    
cat vp8_subpixelvariance8x8_neon.asm           | perl ../../../../build/make/ads2gas.pl >vp8_subpixelvariance8x8_neon_gnu.S       