						#################################################################
						#  									Visualon Makefile Template  							 	#
						#																																#
						#						(Please Keep Below Options Order Unchanged)					#
						#################################################################

# target type
# available: pc, v4(armv4), v5(armv5), v5x(armv5 xscale), v6(armv6), v7(cortex-a8 neon)
VOTT:=v6
 

#top root path
VOTOP:=../../../../../..



# dependent libraries.
VODEPLIBS:= -ldl -lstdc++


# module source
# please modify here to be sure to see the ms.mk which specifies all source info of your module
include ../ms.mk
