#pragma once

#include "voType.h"

const VO_BYTE	MKVID_EBMLHEADER[] = { 0x1a , 0x45 , 0xdf , 0xa3 };

const VO_BYTE	MKVID_SEGMENT[] = { 0x18 , 0x53 , 0x80 , 0x67 };

	const VO_BYTE MKVID_SEGMENT_SEEKHEAD[] = { 0x11 , 0x4d , 0x9b , 0x74 };
		const VO_BYTE MKVID_SEGMENT_SEEKHEAD_SEEK[] = { 0x4d , 0xbb };
			const VO_BYTE MKVID_SEGMENT_SEEKHEAD_SEEK_SEEKID[] = { 0x53 , 0xab };
			const VO_BYTE MKVID_SEGMENT_SEEKHEAD_SEEK_SEEKPOSITION[] = { 0x53 , 0xac };

	const VO_BYTE MKVID_SEGMENT_SEGMENTINFO[] = { 0x15 , 0x49 , 0xa9 , 0x66 };
		const VO_BYTE MKVID_SEGMENT_SEGMENTINFO_DURATION[] = { 0x44 , 0x89 };
		const VO_BYTE MKVID_SEGMENT_SEGMENTINFO_TIMECODESCALE[] = { 0x2a , 0xd7 , 0xb1 };

	const VO_BYTE MKVID_SEGMENT_CLUSTER[] = { 0x1f , 0x43 , 0xb6 , 0x75 };
		const VO_BYTE MKVID_SEGMENT_CLUSTER_TIMECODE[] = { 0xe7 };
		const VO_BYTE MKVID_SEGMENT_CLUSTER_BLOCKGROUP[] = { 0xa0 };
		const VO_BYTE MKVID_SEGMENT_CLUSTER_SIMPLEBLOCK[] = { 0xa3 };
			const VO_BYTE MKVID_SEGMENT_CLUSTER_BLOCKGROUP_BLOCK[] = { 0xa1 };
			const VO_BYTE MKVID_SEGMENT_CLUSTER_BLOCKGROUP_BLOCKDURATION[] = { 0x9b };
			const VO_BYTE MKVID_SEGMENT_CLUSTER_BLOCKGROUP_REFERENCEBLOCK[] = { 0xfb };

	const VO_BYTE MKVID_SEGMENT_TRACKS[] = { 0x16 , 0x54 , 0xae , 0x6b };
		const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY[] = { 0xae };
			const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_TRACKNUMBER[] = { 0xd7 };
			const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_TRACKTYPE[] = { 0x83 };
			const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_FLAGENABLED[] = { 0xb9 };
			const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_FLAGDEFAULT[] = { 0x88 };
			const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_FLAGFORCED[] = { 0x55 , 0xaa };
			const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_DEFAULTDURATION[] = { 0x23 , 0xe3 , 0x83 };
			const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_TRACKTIMECODESCALE[] = { 0x23 , 0x31 , 0x4f };
			const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_LANGUAGE[] = { 0x22 , 0xb5 , 0x9c };
			const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_CODECID[] = { 0x86 };
			const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_CODECPRIVATE[] = { 0x63 , 0xa2 };
			const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_VIDEO[] = { 0xe0 };
				const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_VIDEO_PIXELWIDTH[] = { 0xb0 };
				const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_VIDEO_PIXELHEIGHT[] = { 0xba };
			const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_CONTENTENCODEINGS[] = { 0x6d , 0x80 };
				const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_CONTENTENCODEING[] = { 0x62 , 0x40 };
					const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_CONTENTCOMPRESSION[] = { 0x50 , 0x34 };
						const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_CONTENTCOMPALGO[] = { 0x42 , 0x54 };
						const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_CONTENTCOMPSETTINGS[] = { 0x42 , 0x55 };

			const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_AUDIO[] = { 0xe1 };
				const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_AUDIO_SAMPLEFREQ[] = { 0xb5 };
				const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_AUDIO_CHANNELS[] = { 0x9f };
				const VO_BYTE MKVID_SEGMENT_TRACKS_TRACKENTRY_AUDIO_BITDEPTH[] = { 0x62 , 0x64 };

	const VO_BYTE MKVID_SEGMENT_CUEDATA[] = { 0x1c , 0x53 , 0xbb , 0x6b };
		const VO_BYTE MKVID_SEGMENT_CUEDATA_CUEPOINT[] = { 0xbb };
			const VO_BYTE MKVID_SEGMENT_CUEDATA_CUEPOINT_CUETIME[] = { 0xb3 };
			const VO_BYTE MKVID_SEGMENT_CUEDATA_CUEPOINT_CUETRACKPOSITIONS[] = { 0xb7 };
				const VO_BYTE MKVID_SEGMENT_CUEDATA_CUEPOINT_CUETRACKPOSITIONS_CUETRACK[] = { 0xf7 };
				const VO_BYTE MKVID_SEGMENT_CUEDATA_CUEPOINT_CUETRACKPOSITIONS_CUECLUSTERPOSITION[] = { 0xf1 };
				const VO_BYTE MKVID_SEGMENT_CUEDATA_CUEPOINT_CUETRACKPOSITIONS_CUEBLOCKNUMBER[] = { 0x53 , 0x78 };

	const VO_BYTE MKVID_SEGMENT_ATTACHMENTS[] = { 0x19 , 0x41 , 0xa4 , 0x69 };

	const VO_BYTE MKVID_SEGMENT_CHAPTERS[] = { 0x10 , 0x43 , 0xa7 , 0x70 };

	const VO_BYTE MKVID_SEGMENT_TAGGING[] = { 0x12 , 0x54 , 0xc3 , 0x67 };

