						#################################################################
						#				Visualon Makefile Template 					 	#
						#																#
						#		(Please Keep Below Options Order Unchanged)				#
						#################################################################

# target type
VOTT:=v6

#VODBG=yes

# module type
VOMT:=lib

# module macros
VOMM:=-D_IOS -D_DASH_SOURCE_ -D_SOURCE2 -D_NEW_SOURCEBUFFER #-D_VOLOG_INFO -D_VOLOG_ERROR -D_VOLOG_WARNING -D_VOLOG_RUN

# please specify the name of your module
VOTARGET:=libvoLiveSrcDASH

#dependent static libraries
#do not link shared libraries into your library, it should be link by the top application link
#format: -l+thepath; -l++dependentlibrary(remove the prefix "lib" and suffix "a")
#e.g. vostclibs:=-l../dir -lvoxxxbase  #means your module depends on ../dir/libvoxxxbase.a

# please specify where is the vorelease on your pc, relative path is suggested
# vorelease folder is local on the same level directory with the trunk folder
VORELDIR:=../../../../../../voRelease/iOS/static/v6


# module source
# please modify here to be sure to see the ms.mk which specifies all source info of your module
include ../source.mk

# please modify here to be sure to see the eclair.mk
include ../../../../../build/ios.mk

# please modify here to be sure to see the doit.mk
include ../../../../../build/idoit.mk

