/* config.h.  Generated by configure.  */
#ifndef __CONFIG_H__
#define __CONFIG_H__

#define CHAR_BIT				8

#define MAX_SCFBD				4
#define MAX_NGRAN				2	
#define MAX_NCHAN				2	
#define MAX_NSAMP				576	
#define SBLIMIT					32

#define VBUF_LENGTH				(17 * 2 * SBLIMIT)

# define F_FRACBITS		28
# define F_ONE			0x10000000
#define MAX_32			(int)0x7fffffffL
#define MIN_32			(int)0x80000000L

#define MAX_16			(short)0x7fff
#define MIN_16			(short)0x8000

#ifndef MAX
#define MAX(a,b)	((a) > (b) ? (a) : (b))
#endif

#ifndef MIN
#define MIN(a,b)	((a) < (b) ? (a) : (b))
#endif

#endif