@************************************************************************
@									                                    *
@	VisualOn, Inc Confidential and Proprietary, 2009		            *
@	written by John							 	                                    *
@***********************************************************************/

	@AREA    |.text|, CODE, READONLY
#include "../../../../Inc/voVP6DecID.h"
	.section .text

	.END