# File parser common files.
# rodney zhang
# 2012.03.31


# Path variables for common files that are used in file parsers.
TRUNK_PATH:=../../../../..
TRUNK_INCLUDE_PATH:=$(TRUNK_PATH)/Include
TRUNK_INCLUDE_VOME_PATH:=$(TRUNK_INCLUDE_PATH)/vome
TRUNK_COMMON_PATH:=$(TRUNK_PATH)/Common
TRUNK_COMMON_NETWORK_PATH:=$(TRUNK_COMMON_PATH)/NETWORK
TRUNK_MFW_VOME_COMMON_PATH:=$(TRUNK_PATH)/MFW/voME/Common
TRUNK_SOURCE_PATH:=$(TRUNK_PATH)/Source
TRUNK_SOURCE_FILE_PATH:=$(TRUNK_SOURCE_PATH)/File
TRUNK_SOURCE_FILE_COMMON_PATH:=$(TRUNK_SOURCE_FILE_PATH)/Common
TRUNK_SOURCE_FILE_METADATA_PATH:=$(TRUNK_SOURCE_FILE_PATH)/MetaData
TRUNK_SOURCE_FILE_XML_PATH:=$(TRUNK_SOURCE_FILE_PATH)/XML
TRUNK_SOURCE_MTV_PATH:=$(TRUNK_SOURCE_PATH)/MTV
TRUNK_SOURCE_MTV_COMMON_PATH:=$(TRUNK_SOURCE_MTV_PATH)/Common
TRUNK_SOURCE_MTV_LIVESOURCE_COMMON_PATH:=$(TRUNK_SOURCE_MTV_PATH)/LiveSource/Common
TRUNK_SOURCE_MTV_LIVESOURCE_ATSCMH_COMMON_PATH:=$(TRUNK_SOURCE_MTV_PATH)/LiveSource/ATSCMH/Common
TRUNK_SOURCE_MTV_CMMB_TINYXML_PATH:=$(TRUNK_SOURCE_MTV_PATH)/CMMB/TinyXML
TRUNK_UTILITY_UTF8_PATH:=$(TRUNK_PATH)/Utility/voutf8conv


# please list all directories that all source files relative to your module(.h .c .cpp) locate 
VOSRCDIR:= \
	$(TRUNK_INCLUDE_PATH) \
	$(TRUNK_COMMON_PATH) \
	$(TRUNK_COMMON_NETWORK_PATH) \
	$(TRUNK_SOURCE_FILE_COMMON_PATH) \
	$(TRUNK_SOURCE_FILE_METADATA_PATH) \
	$(TRUNK_SOURCE_FILE_XML_PATH) \
	$(TRUNK_INCLUDE_VOME_PATH) \
	$(TRUNK_MFW_VOME_COMMON_PATH) \
	$(TRUNK_SOURCE_MTV_COMMON_PATH) \
	$(TRUNK_SOURCE_MTV_LIVESOURCE_COMMON_PATH) \
	$(TRUNK_SOURCE_MTV_LIVESOURCE_ATSCMH_COMMON_PATH) \
	$(TRUNK_SOURCE_MTV_CMMB_TINYXML_PATH) \
	$(TRUNK_UTILITY_UTF8_PATH) \

# please list all objects needed by your module here
VOMSRC:= \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/CBaseReader.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/CBaseStreamFileIndex.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/CBaseStreamFileReader.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/CBaseStreamFileTrack.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/CBaseTrack.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/CBitrateMap.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/CCodeCC.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/CGBuffer.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/CGFileChunk.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/CMemPool.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/CvoBaseDrmCallback.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/CvoBaseFileOpr.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/CvoBaseMemOpr.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/CvoFileParser.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/CvoStreamFileDataParser.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/fCodec.c \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/fortest.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/vo_file_io.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/vo_file_parser.cpp \
	$(TRUNK_SOURCE_FILE_COMMON_PATH)/vo_thread.cpp \
	\
	$(TRUNK_SOURCE_FILE_METADATA_PATH)/CBaseMetaData.cpp \
	$(TRUNK_SOURCE_FILE_METADATA_PATH)/CID3MetaData.cpp \
	\
	$(TRUNK_SOURCE_MTV_COMMON_PATH)/CAnalyseAAC.cpp \
	$(TRUNK_SOURCE_MTV_COMMON_PATH)/CAnalyseH264.cpp \
	$(TRUNK_SOURCE_MTV_COMMON_PATH)/CAnalyseMPEG4.cpp \
	$(TRUNK_SOURCE_MTV_COMMON_PATH)/CBaseAnalyseData.cpp \
	$(TRUNK_SOURCE_MTV_COMMON_PATH)/CBaseParser.cpp \
	$(TRUNK_SOURCE_MTV_COMMON_PATH)/CBaseTools.cpp \
	$(TRUNK_SOURCE_MTV_COMMON_PATH)/CDumper.cpp \
	$(TRUNK_SOURCE_MTV_COMMON_PATH)/CMTVReader.cpp \
	$(TRUNK_SOURCE_MTV_COMMON_PATH)/CMTVStreamFileIndex.cpp \
	$(TRUNK_SOURCE_MTV_COMMON_PATH)/adtshead.cpp \
	$(TRUNK_SOURCE_MTV_COMMON_PATH)/adtspacker.cpp \
	$(TRUNK_SOURCE_MTV_COMMON_PATH)/adtsparser.cpp \
	\
	$(TRUNK_SOURCE_MTV_LIVESOURCE_COMMON_PATH)/CLiveSrcBase.cpp \
	$(TRUNK_SOURCE_MTV_LIVESOURCE_COMMON_PATH)/CLiveParserBase.cpp \
	$(TRUNK_SOURCE_MTV_LIVESOURCE_COMMON_PATH)/ConfigFile.cpp \
	$(TRUNK_SOURCE_MTV_LIVESOURCE_COMMON_PATH)/ChannelInfo.cpp \
	\
	$(TRUNK_SOURCE_MTV_LIVESOURCE_ATSCMH_COMMON_PATH)/base64.cpp \
	$(TRUNK_SOURCE_MTV_LIVESOURCE_ATSCMH_COMMON_PATH)/strutil.cpp \
	\
	$(TRUNK_SOURCE_MTV_CMMB_TINYXML_PATH)/tinystr.cpp \
	$(TRUNK_SOURCE_MTV_CMMB_TINYXML_PATH)/tinyxml.cpp \
	$(TRUNK_SOURCE_MTV_CMMB_TINYXML_PATH)/tinyxmlerror.cpp \
	$(TRUNK_SOURCE_MTV_CMMB_TINYXML_PATH)/tinyxmlparser.cpp \
	\
	$(TRUNK_UTILITY_UTF8_PATH)/voutf8conv.c
